// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type User struct {
	ID          int64
	Email       string
	UserName    string
	Password    string
	PhoneNumber sql.NullString
	Role        string
	Location    sql.NullString
	CreatedAt   sql.NullTime
}
